### PR TITLE
Add size command

### PR DESCRIPTION
**Pull request by twe4ked**
It doesn't handle STDIN yet. Is there an example of a command that takes STDIN or a list of files?

I'm not sure what you meant by “max-length”. I took it to mean bytes and I also included chars.

Happy to make any changes.

Closes https://github.com/wycats/nushell/issues/17.

### CODE REVIEW

**Comment by wycats** [comment]
Thanks! This is great.

We're still getting streaming stdin right, so we don't need to block on that for this patch.

I think we should probably remove the `total` row and create a generalized facility for subtotaling tables of this sort. I'm happy to merge this if you remove that row :)

**Comment by twe4ked** [comment]
I've removed the total row. Did you see [my comment on #17](https://github.com/wycats/nushell/issues/17#issuecomment-495955790) around naming?

**Comment by jonathandturner** [comment]
> I've removed the total row. Did you see [my comment on #17](https://github.com/wycats/nushell/issues/17#issuecomment-495955790) around naming?

Yeah, we can change the name if there's a better one. I'm going to land this so we're all up to date. But if you want to switch to "count", we can do that.  We're still very much trying to figure out what command names work best.

**Comment by mb21** [comment]
Yeah, `size` sounds like it should return a filesize or something of [type bytes](https://book.nushell.sh/en/types_of_data#bytes). `count` sounds good to me, like the 'count' in the unix  `wc` (wordcount) command.

**Pull request merged**
