### PR TITLE
Make sure to enable ANSI for Win10

### PR DESCRIPTION
**Pull request by jonathandturner**
Go ahead and use ansi_term to enable ANSI support on Windows 10

### CODE REVIEW

**Comment by wycats** [comment]
Does this PR work as a noop on non-Windows?

**Comment by jonathandturner** [comment]
Unknown.  It's from https://github.com/ogham/rust-ansi-term under Basic Usage.  Lemme see if I have a Linux image around

**Comment by wycats** [comment]
It looks like it needs a #[cfg(windows)] because I only see it here: https://github.com/ogham/rust-ansi-term/blob/af47bb56363e58b0c133db27831bcc0d1f10fb0a/src/windows.rs#L10

**Comment by jonathandturner** [comment]
@wycats updated

**Pull request merged**
